seed: 13345
sim1:
  I0: 5
  L: 10
  N_total: 200
  beta: 0.35
  boundary: reflect
  curves_png: images/sim1/sim1_curvas.png
  dt: 1.0
  fps: 20
  gamma: 0.08
  out_gif: images/sim1/sim1.gif
  r: 0.6
  steps: 230
  vmax: 0.8
sim2:
  I0: 5
  M: 60
  N: 60
  SEED: 42
  T: 500
  beta: 0.3
  curves_png: images/sim2/sim2_curvas.png
  fps: 12
  gamma: 0.05
  interval: 60
  out_gif: images/sim2/sim2.gif
  r: 1
  save_gif: true
